name: snipeit

on:
  push:
    branches: [ devcontainer ]
  
jobs:

  build:
    name: CI/CD-snipeit
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@devcontainer
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          whoami
          cd /var/html/www/Snipe-IT-2
          sudo git pull origin devcontainer
          sudo docker-compose up --build -d
