name: snipeit

on:
  push:
    branches: [ devcontainer ]
  
jobs:

  build:
    name: CI/CD-snipeit
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: 34.227.194.234
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          whoami
          cd /srv/Snipe-IT-2
          sudo git pull origin devcontainer
