---
#
#   This workflow will login into AWS , buid an image from docker file, push it to AWS ECR repo.
#   Author : Akshay
#   Date-Created: 17-11-2022 | Date-Last-Modified: 21-11-2022
#

name: Docker CI to AWS ECR

on:
  # push:
  #   branches:
  #     - main
  #  pull_request:
  #    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"

      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: snipe2
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker-compose -f "docker-compose.yml" up -d --build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # - name: Start container
      #   run: |
      #     docker-compose -f "docker-compose.yml" up -d --build
      #     docker ps -a
      #     docker image ls
